// react-typescript/src/App.tsx
import * as React from 'react';
import './App.css';
import { TVChartContainer } from './components/TVChartContainer/index';
import { version } from './charting_library';

const App = () => {
	return (
		<div className={ 'App' }>
			<header className={ 'App-header' }>
				<h1 className={ 'App-title' }>
					TradingView Charting Library and React Integration Example { version() }
				</h1>
			</header>
			<TVChartContainer />
		</div>
	);
};

export default App;

// angular5/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'TradingView Charting Library and Angular 5 Integration Example';
}

<div class="app-container">
	<div class="app-header-container">
		<h1 class="app-header">{{ title }}</h1>
	</div>
	<app-tv-chart-container></app-tv-chart-container>
</div>
